alter session set "_ORACLE_SCRIPT"=true;

CREATE USER TAG IDENTIFIED BY zx6j1bft
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO TAG;
--GRANT PLUSTRACE TO TAG;
GRANT RESOURCE TO TAG;
GRANT SELECT_CATALOG_ROLE TO TAG;

GRANT CREATE DATABASE LINK TO TAG;
GRANT CREATE VIEW TO TAG;
GRANT UNLIMITED TABLESPACE TO TAG;
