@/dba/admin/advocate/enchildfk STG_CLME_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_AWARD
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_BALANCING
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_CODEFENDANT
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_CONSENT
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_COUNSEL
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_COVERAGE
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_DAMAGE
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_DOCUMENT
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_EMPLOYEE
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_EXPERT
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_NEGOTIATION
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_NOTES
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_PARTY
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_RES_BAL
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_SCHP
@/dba/admin/advocate/enchildfk STG_CLML_CLAIM_SETTLEMENT_DFND
@/dba/admin/advocate/enchildfk STG_CLML_CLOSURE_SUMMARY
@/dba/admin/advocate/enchildfk STG_CLML_EXCEMPT_SCHP_RULES
@/dba/admin/advocate/enchildfk STG_CLML_EXEMPT_RULES
@/dba/admin/advocate/enchildfk STG_CLML_FINANCIAL_PAY_DTL
@/dba/admin/advocate/enchildfk STG_CLML_FINANCIAL_PAY_HDR
@/dba/admin/advocate/enchildfk STG_CLML_FINANCIAL_REC_TRAN
@/dba/admin/advocate/enchildfk STG_CLML_FINANCIAL_RES_TRAN
@/dba/admin/advocate/enchildfk STG_CLML_LITIGATION
@/dba/admin/advocate/enchildfk STG_CLML_LITIGATION_EVENT
@/dba/admin/advocate/enchildfk STG_CLML_PAYMENT_ADDR_HIST
@/dba/admin/advocate/enchildfk STG_CLML_POLICY_SNAPSHOT
@/dba/admin/advocate/enchildfk STG_CLML_RETENTION_BILL_RPT
@/dba/admin/advocate/enchildfk STG_CLML_RETENTION_BILL_SMT
@/dba/admin/advocate/enchildfk STG_CLML_SETTLEMENT_AUTHORITY
@/dba/admin/advocate/enchildfk STG_CONV_COLUMN_GROUP
@/dba/admin/advocate/enchildfk STG_CONV_GT_ENTITY_TO_MOVE
@/dba/admin/advocate/enchildfk STG_CONV_LOAD
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_COLUMN
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_ERR_COUNT
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_HIST
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_PARM
@/dba/admin/advocate/enchildfk STG_CONV_LOAD_TABLE
@/dba/admin/advocate/enchildfk STG_CONV_STATS
@/dba/admin/advocate/enchildfk STG_CONV_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_CONV_VALIDATION_RULE
@/dba/admin/advocate/enchildfk STG_EDLE_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_EDLL_DOCUCORP_E_IMAGE
@/dba/admin/advocate/enchildfk STG_EMPE_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_SCME_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_SCML_CMS
@/dba/admin/advocate/enchildfk STG_SCML_CMS_DIRMKT
@/dba/admin/advocate/enchildfk STG_SPLE_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_SPLL_ADDITIONAL_INSURED
@/dba/admin/advocate/enchildfk STG_SPLL_BLENDING_DETAIL
@/dba/admin/advocate/enchildfk STG_SPLL_COVERAGE
@/dba/admin/advocate/enchildfk STG_SPLL_DEBIT_CREDIT
@/dba/admin/advocate/enchildfk STG_SPLL_EXC_EFF_DT_POL_ISSUES
@/dba/admin/advocate/enchildfk STG_SPLL_EXEMPT_RULES
@/dba/admin/advocate/enchildfk STG_SPLL_INSURED
@/dba/admin/advocate/enchildfk STG_SPLL_INSURED_NOTES
@/dba/admin/advocate/enchildfk STG_SPLL_INSURED_PLAN_GRP_ASSO
@/dba/admin/advocate/enchildfk STG_SPLL_INSURED_SCHEDULE
@/dba/admin/advocate/enchildfk STG_SPLL_MAILING_ADDRESS
@/dba/admin/advocate/enchildfk STG_SPLL_MONTHLY_PREMIUM
@/dba/admin/advocate/enchildfk STG_SPLL_MONTHLY_PREMIUM_HIST
@/dba/admin/advocate/enchildfk STG_SPLL_MONTHLY_TAXES_FEES
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY_ADDR_ASSOC
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY_BAL_EXCEPTIONS
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY_EMPLOYEE
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY_TERM
@/dba/admin/advocate/enchildfk STG_SPLL_POLICY_TERM_NOTES
@/dba/admin/advocate/enchildfk STG_SPLL_PRIOR_ACTS_BLENDING
@/dba/admin/advocate/enchildfk STG_SPLL_PRIOR_ACTS_COV_LIMIT
@/dba/admin/advocate/enchildfk STG_SPLL_RETENTION_COVERAGE
@/dba/admin/advocate/enchildfk STG_SPLL_RETENTION_POLICY
@/dba/admin/advocate/enchildfk STG_SPLL_SEGMENT
@/dba/admin/advocate/enchildfk STG_SPLL_SPECIALTY
@/dba/admin/advocate/enchildfk STG_SPLL_TRANS_OFFSET_ONSET
@/dba/admin/advocate/enchildfk STG_SPLL_TRANS_RECAP
@/dba/admin/advocate/enchildfk STG_SPLL_UNEARNED_PREM
@/dba/admin/advocate/enchildfk STG_STLL_OLD_NEW_CLM_NUM_XREF
@/dba/admin/advocate/enchildfk STG_STLL_OLD_NEW_POL_NUM_XREF
@/dba/admin/advocate/enchildfk STG_TKME_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_TKML_TM_TASK
@/dba/admin/advocate/enchildfk STG_UCLL_CLAIM_SCHP_OFFSET
@/dba/admin/advocate/enchildfk STG_UCLL_UNCONVERTED_CLAIM
@/dba/admin/advocate/enchildfk STG_VISE_VALIDATION_ERROR_LOG
@/dba/admin/advocate/enchildfk STG_VISL_BILL_ACCT
@/dba/admin/advocate/enchildfk STG_VISL_BILL_ACCT_BAL
@/dba/admin/advocate/enchildfk STG_VISL_INSTALLMENT
