DROP PUBLIC SYNONYM ACOMMON;
DROP MATERIALIZED VIEW MVDATA.ACOMMON;
CREATE MATERIALIZED VIEW MVDATA.ACOMMON 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE MV_DATA
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT "ACOMMON"."A04_ANUM" "A04_ANUM","ACOMMON"."J03_SUB_ANUM" "J03_SUB_ANUM","ACOMMON"."A04_TRANS_ANUM" "A04_TRANS_ANUM","ACOMMON"."J03_SUB_TRANS_ANUM" "J03_SUB_TRANS_ANUM","ACOMMON"."E04_ANAMNUM" "E04_ANAMNUM","ACOMMON"."D15_STATUS_FDATE" "D15_STATUS_FDATE","ACOMMON"."D14_STATUS" "D14_STATUS","ACOMMON"."X66_MASTER_AGENT" "X66_MASTER_AGENT","ACOMMON"."A2K_COLLECTOR" "A2K_COLLECTOR","ACOMMON"."D90_CONTACT" "D90_CONTACT","ACOMMON"."E04_SNAMNUM" "E04_SNAMNUM","ACOMMON"."D14_AGT_REN_STATUS" "D14_AGT_REN_STATUS","ACOMMON"."D15_AGT_REN_FDATE" "D15_AGT_REN_FDATE","ACOMMON"."W59_AG_UW_STATUS" "W59_AG_UW_STATUS","ACOMMON"."D88_ROL_SPRD_1ST" "D88_ROL_SPRD_1ST","ACOMMON"."DIARY_CANCEL" "DIARY_CANCEL","ACOMMON"."AGENT_CAPTIVE_TYPE_CODE" "AGENT_CAPTIVE_TYPE_CODE" FROM "ACOMMON"@TO_STAR "ACOMMON";
CREATE UNIQUE INDEX MVDATA.AK1ACOMMON ON MVDATA.ACOMMON
(A04_ANUM, J03_SUB_ANUM)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.ACOMMON TO SECURITY;
GRANT SELECT ON  MVDATA.ACOMMON TO security_read;
GRANT SELECT ON  MVDATA.ACOMMON TO itprd_user;
CREATE PUBLIC SYNONYM ACOMMON FOR ACOMMON;

DROP PUBLIC SYNONYM HEALTHCARE_PROF;
DROP MATERIALIZED VIEW MVDATA.HEALTHCARE_PROF;
CREATE MATERIALIZED VIEW MVDATA.HEALTHCARE_PROF 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
TABLESPACE MV_INDEX
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT	e04_orignum, b79_unit, d78_status,
	n60_specialty, n60_sub_specialty, b41_birthdate,
	a4j_prof_salute
FROM	healthcare_prof@to_star;

CREATE UNIQUE INDEX MVDATA.XPKHEALTHCARE_PROF ON MVDATA.HEALTHCARE_PROF
(E04_ORIGNUM)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;

CREATE INDEX MVDATA.IE1HEALTHCARE_PROF ON MVDATA.HEALTHCARE_PROF
(B41_BIRTHDATE)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;

GRANT SELECT ON MVDATA.HEALTHCARE_PROF TO SECURITY;
CREATE PUBLIC SYNONYM HEALTHCARE_PROF FOR HEALTHCARE_PROF;

DROP PUBLIC SYNONYM NAME_ADDRESS;


DROP MATERIALIZED VIEW MVDATA.NAME_ADDRESS;

CREATE MATERIALIZED VIEW MVDATA.NAME_ADDRESS 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE MV_DATA
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT 	e04_namenum, e04_orignum, individual_ind,
	b27_name1, b27_name2, last_name,
	first_name, middle_initial, name_suffix,
	b28_addr1, b28_addr2, b30_city,
	b31_state, b32_zip, n11_homephone,
	t50_workphone, b28_email_addr,
	e04_next, h60_fein_ssn, b28_alt_addr1,
	alt_addr_type, b30_alt_city, b31_alt_state
FROM name_address@to_star;

CREATE INDEX MVDATA.IE1NAME_ADDRESS ON MVDATA.NAME_ADDRESS
(E04_ORIGNUM)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
CREATE INDEX MVDATA.IE2NAME_ADDRESS ON MVDATA.NAME_ADDRESS
(H60_FEIN_SSN)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.NAME_ADDRESS TO SECURITY;
CREATE PUBLIC SYNONYM NAME_ADDRESS FOR NAME_ADDRESS;

DROP PUBLIC SYNONYM NAME_XREF;


DROP MATERIALIZED VIEW MVDATA.NAME_XREF;

CREATE MATERIALIZED VIEW MVDATA.NAME_XREF 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE MV_DATA
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT "NAME_XREF"."T91_ENTITY_KEY" "T91_ENTITY_KEY","NAME_XREF"."A06_EDITION" "A06_EDITION","NAME_XREF"."T91_ENTITY_KEYTYPE" "T91_ENTITY_KEYTYPE","NAME_XREF"."B25_NAMETYPE" "B25_NAMETYPE","NAME_XREF"."E04_ORIGNUM" "E04_ORIGNUM","NAME_XREF"."A08_FDATE" "A08_FDATE","NAME_XREF"."A09_XDATE" "A09_XDATE","NAME_XREF"."B79_UNIT" "B79_UNIT","NAME_XREF"."F67_SPECIAL1" "F67_SPECIAL1","NAME_XREF"."F67_SPECIAL2" "F67_SPECIAL2","NAME_XREF"."T29_ITEM" "T29_ITEM" FROM "NAME_XREF"@TO_STAR "NAME_XREF";
CREATE INDEX MVDATA.IE1NAME_XREF ON MVDATA.NAME_XREF
(E04_ORIGNUM)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
CREATE INDEX MVDATA.IE2NAME_XREF ON MVDATA.NAME_XREF
(T91_ENTITY_KEY, A06_EDITION)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.NAME_XREF TO SECURITY;
CREATE PUBLIC SYNONYM NAME_XREF FOR NAME_XREF;

DROP PUBLIC SYNONYM PCOMMON;


DROP MATERIALIZED VIEW MVDATA.PCOMMON;

CREATE MATERIALIZED VIEW MVDATA.PCOMMON 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE MV_INDEX
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT	a00_pnum, a06_edition, t91_pol_key,
	a08_fdate, a09_xdate, a29_rec_fdate,
	a30_rec_xdate, e04_ins_orignum, b98_policy_type,
	d14_status
FROM pcommon@to_star;
CREATE UNIQUE INDEX MVDATA.XPKPCOMMON ON MVDATA.PCOMMON
(A00_PNUM, A06_EDITION, T91_POL_KEY)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.PCOMMON TO SECURITY;
CREATE PUBLIC SYNONYM PCOMMON FOR PCOMMON;

DROP PUBLIC SYNONYM PSCHEDULE;

DROP MATERIALIZED VIEW MVDATA.PSCHEDULE;
CREATE MATERIALIZED VIEW MVDATA.PSCHEDULE 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE MV_DATA
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT	a00_pnum, a06_edition, t29_item,
	b79_unit, e04_orignum, a29_fdate,
	a30_xdate
FROM	pschedule@to_star;
CREATE UNIQUE INDEX MVDATA.XPKPSCHEDULE ON MVDATA.PSCHEDULE
(A00_PNUM, A06_EDITION, B79_UNIT, T29_ITEM)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.PSCHEDULE TO SECURITY;
CREATE PUBLIC SYNONYM PSCHEDULE FOR PSCHEDULE;

DROP PUBLIC SYNONYM PUNIT;

DROP MATERIALIZED VIEW MVDATA.PUNIT;
CREATE MATERIALIZED VIEW MVDATA.PUNIT 
TABLESPACE MV_DATA
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE MV_INDEX
REFRESH FORCE ON DEMAND
WITH ROWID
AS 
SELECT	a00_pnum, a06_edition, t91_punit_key,
	b79_unit, e01_transnum, d78_status,
	w47_fdate, w48_xdate, c86_unitdesc,
	e04_loc_orignum, b80_userline
FROM	punit@to_star;

CREATE UNIQUE INDEX MVDATA.XPKPUNIT ON MVDATA.PUNIT
(A00_PNUM, A06_EDITION, T91_PUNIT_KEY)
LOGGING
TABLESPACE MV_INDEX
NOPARALLEL;
GRANT SELECT ON  MVDATA.PUNIT TO SECURITY;
CREATE PUBLIC SYNONYM PUNIT FOR PUNIT;

