>> /tdcdv2/external/claim_response_detail.bad
>> /tdcdv2/external/claim_response_header.bad
>> /tdcdv2/external/claim_response_trailer.bad
>> /tdcdv2/external/query_response_detail.bad
>> /tdcdv2/external/query_response_detail.dis
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/rate_load.txt
>> /tdcdv2/external/claim.bad
>> /tdcdv2/external/awards.bad
>> /tdcdv2/external/claim_bal.bad
>> /tdcdv2/external/claim_codefendant.bad
>> /tdcdv2/external/claim_counsel.bad
>> /tdcdv2/external/claim_cov_info.bad
>> /tdcdv2/external/damages.bad
>> /tdcdv2/external/claim_employee.bad
>> /tdcdv2/external/claim_expert.bad
>> /tdcdv2/external/claim_party.bad
>> /tdcdv2/external/claim_res_bal.bad
>> /tdcdv2/external/claim_schp.bad
>> /tdcdv2/external/closure_summary.bad
>> /tdcdv2/external/financials_dtl.bad
>> /tdcdv2/external/financials_hdr.bad
>> /tdcdv2/external/financials_rec.bad
>> /tdcdv2/external/financials_res.bad
>> /tdcdv2/external/litigation.bad
>> /tdcdv2/external/litigation_event.bad
>> /tdcdv2/external/payment_addr_hist.bad
>> /tdcdv2/external/policy_snapshot.bad
>> /tdcdv2/external/retention_bill_rpt.bad
>> /tdcdv2/external/retention_bill_smt.bad
>> /tdcdv2/external/claim.txt
>> /tdcdv2/external/awards.txt
>> /tdcdv2/external/claim_bal.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/claim_cov_info.txt
>> /tdcdv2/external/damages.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/claim_res_bal.txt
>> /tdcdv2/external/claim_schp.txt
>> /tdcdv2/external/closure_summary.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/litigation.txt
>> /tdcdv2/external/litigation_event.txt
>> /tdcdv2/external/payment_addr_hist.txt
>> /tdcdv2/external/policy_snapshot.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/claim.txt
>> /tdcdv2/external/awards.txt
>> /tdcdv2/external/claim_bal.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/claim_cov_info.txt
>> /tdcdv2/external/damages.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/contacts.txt
>> /tdcdv2/external/claim_res_bal.txt
>> /tdcdv2/external/claim_schp.txt
>> /tdcdv2/external/closure_summary.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/litigation.txt
>> /tdcdv2/external/litigation_event.txt
>> /tdcdv2/external/payment_addr_hist.txt
>> /tdcdv2/external/policy_snapshot.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/financials.txt
>> /tdcdv2/external/DE_Image.bad
>> /tdcdv2/external/DE_Image.txt
>> /tdcdv2/external/DE_Image.txt
>> /tdcdv2/external/Employees.bad
>> /tdcdv2/external/CMS.txt
>> /tdcdv2/external/CMS.txt
>> /tdcdv2/external/actprem_hist.bad
>> /tdcdv2/external/actprem_misc.bad
>> /tdcdv2/external/additional_insured.bad
>> /tdcdv2/external/adjustment.bad
>> /tdcdv2/external/coverage.bad
>> /tdcdv2/external/eis_ytd.bad
>> /tdcdv2/external/facility_coverage.bad
>> /tdcdv2/external/gl_balancing.bad
>> /tdcdv2/external/insured.bad
>> /tdcdv2/external/plan_group.bad
>> /tdcdv2/external/policy_common.bad
>> /tdcdv2/external/prior_acts_cov.bad
>> /tdcdv2/external/retention.bad
>> /tdcdv2/external/insured_schedule.bad
>> /tdcdv2/external/trans_detail.bad
>> /tdcdv2/external/trans_hist.bad
>> /tdcdv2/external/actprem_hist.txt
>> /tdcdv2/external/actprem_misc.txt
>> /tdcdv2/external/additional_insured.txt
>> /tdcdv2/external/adjustment.txt
>> /tdcdv2/external/coverage.txt
>> /tdcdv2/external/eis_ytd.txt
>> /tdcdv2/external/facility_coverage.txt
>> /tdcdv2/external/gl_balancing.txt
>> /tdcdv2/external/insured.txt
>> /tdcdv2/external/plan_group.txt
>> /tdcdv2/external/policy_common.txt
>> /tdcdv2/external/prior_acts_cov.txt
>> /tdcdv2/external/retention.txt
>> /tdcdv2/external/insured_schedule.txt
>> /tdcdv2/external/trans_detail.txt
>> /tdcdv2/external/trans_hist.txt
>> /tdcdv2/external/actprem_hist.txt
>> /tdcdv2/external/actprem_misc.txt
>> /tdcdv2/external/additional_insured.txt
>> /tdcdv2/external/adjustment.txt
>> /tdcdv2/external/coverage.txt
>> /tdcdv2/external/eis_ytd.txt
>> /tdcdv2/external/facility_coverage.txt
>> /tdcdv2/external/gl_balancing.txt
>> /tdcdv2/external/insured.txt
>> /tdcdv2/external/plan_group.txt
>> /tdcdv2/external/policy_common.txt
>> /tdcdv2/external/prior_acts_cov.txt
>> /tdcdv2/external/retention.txt
>> /tdcdv2/external/insured_schedule.txt
>> /tdcdv2/external/trans_detail.txt
>> /tdcdv2/external/trans_hist.txt
>> /tdcdv2/external/claim_xref.bad
>> /tdcdv2/external/policy_xref.bad
>> /tdcdv2/external/claim_xref.txt
>> /tdcdv2/external/policy_xref.txt
>> /tdcdv2/external/claim_xref.txt
>> /tdcdv2/external/policy_xref.txt
>> /tdcdv2/external/tm_task.bad
>> /tdcdv2/external/tm_task.txt
>> /tdcdv2/external/tm_task.txt
>> /tdcdv2/external/claim_schp_offset.bad
>> /tdcdv2/external/claim_unc.bad
>> /tdcdv2/external/claim_schp_offset.txt
>> /tdcdv2/external/claim_unc.txt
>> /tdcdv2/external/claim_schp_offset.txt
>> /tdcdv2/external/claim_unc.txt
>> /tdcdv2/external/bill_acct.bad
>> /tdcdv2/external/billacctbal.bad
>> /tdcdv2/external/installment.bad
>> /tdcdv2/external/bill_acct.txt
>> /tdcdv2/external/billacctbal.txt
>> /tdcdv2/external/installment.txt
>> /tdcdv2/external/bill_acct.txt
>> /tdcdv2/external/billacctbal.txt
>> /tdcdv2/external/installment.txt
>> /tdcdv2/external/tin_response_detail.bad
>> /tdcdv2/external/tin_response_header.bad
>> /tdcdv2/external/tin_response_trailer.bad
>> /tdcdv2/external/tribute_opco.txt
>> /tdcdv2/external/tribute_opco.bad
>> /tdcdv2/external/tribute_opco.dis
>> /tdcdv2/external/tribute_opco.log
