#!/bin/sh

CMD="mail"
# CMD="uptime"
# CMD="/mnt/dba/admin/meminfo.sh | grep \"Huge Memory\""
# CMD="ls -l /tmp/data_load_test"
# CMD="grep data_load /home/oracle/.bash_history"
# CMD="/mnt/dba/admin/asm_diskstring.sh"
CMD="/mnt/dba/admin/run_script_all_sid.sh /mnt/dba/scripts/temp.sql"
# CMD="/mnt/dba/admin/run_script_all_sid.sh /mnt/dba/scripts/chk_partitioning_usage.sql"
# CMD="/mnt/dba/admin/run_script_all_sid.sh /mnt/dba/scripts/syn_orphans_show.sql"
# CMD="/mnt/dba/admin/run_shell_script_all_sid.sh /mnt/dba/admin/show_iop_usage.sh"
# CMD="/mnt/dba/admin/run_shell_script_all_sid.sh /mnt/dba/admin/log_segment_history.sh"
# CMD="/mnt/dba/admin/chk_asm_spare_candidate_disk.sh"
# CMD="ls -1 /u01/app/12.1.0.1/grid/rdbms/audit | wc -l"
# CMD="ps x | grep backup"
# CMD="df -m | grep backup"
# CMD="md5sum /u01/app/oracle/admin/common_scripts/backup_database_PDB.sh"
# CMD="md5sum /usr/local/bin/oraenv"
# CMD="md5sum /usr/local/bin/dbhome"
# CMD="md5sum /u01/app/oracle/admin/common_scripts/check.sh"
# CMD="find /u01/app/oracle/diag/rdbms/*/*/trace -name alert*.log -exec grep ORA-10561 {} \;"
# CMD="ls -l /etc/rc.d/init.d/gcstartup"
# CMD="ls -l /home/oracle/dba | grep upgrade"
# CMD="find /home/oracle/dba -name recover*"
# CMD="scp -p dbmon04:/u01/app/oracle/admin/common_scripts/check.sh /u01/app/oracle/admin/common_scripts/check.sh"
# CMD="/mnt/dba/admin/run_script_all_sid.sh /mnt/dba/projects/DBA-5926/DBA-5926.sql"

echo ".................... sora10"
ssh -o UserKnownHostsFile=~/.ssh/known_hosts sora10 "$CMD"
echo ".................... sora11"
ssh -o UserKnownHostsFile=~/.ssh/known_hosts sora11 "$CMD"
echo ".................... sora12"
ssh -o UserKnownHostsFile=~/.ssh/known_hosts sora12 "$CMD"
echo ".................... sora13"
ssh -o UserKnownHostsFile=~/.ssh/known_hosts sora13 "$CMD"
echo ".................... sora14"
ssh -o UserKnownHostsFile=~/.ssh/known_hosts sora14 "$CMD"
