#!/bin/sh

if [ "$1" = "" ]
then
  echo
  echo "   Usage: $0 <ORACLE_SID>"
  echo
  echo "   Example: $0 novadev"
  echo
  exit
fi

export ORACLE_SID=$1
export ORAENV_ASK=NO
. /usr/local/bin/oraenv

. /dba/admin/dba.lib

tns=`get_tns_from_orasid $ORACLE_SID`
securityusername=security
securityuserpwd=`get_user_pwd $tns $securityusername`

. /dba/admin/dba.lib

sqlplus -s /nolog << EOF
connect $securityusername/$securityuserpwd

@/dba/admin/post_restore/SEC_CR32917.SQL
commit;

INSERT INTO USER_ACCESS_TABLE(
    USER_ACCESS_ID,
    USER_ID,
    SECURED_OBJECT_ID,
    ACCESS_TYPE_CODE,
    CREATED_BY,
    CREATED_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATED_DATE,
    ROW_VERSION
)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       1030179,
       'RW',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE ROLE IF IT IS ALREADY PRESENT
AND NOT EXISTS (SELECT 1
                FROM USER_ACCESS_TABLE A
                WHERE A.USER_ID = U.USER_ID
                AND SECURED_OBJECT_ID = 1030179);

--ADD PC-APPROVE PAYMENTS OVERRIDE
INSERT INTO USER_ACCESS_TABLE(
    USER_ACCESS_ID,
    USER_ID,
    SECURED_OBJECT_ID,
    ACCESS_TYPE_CODE,
    CREATED_BY,
    CREATED_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATED_DATE,
    ROW_VERSION
)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       12361511,
       'RW',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE ROLE IF IT IS ALREADY PRESENT
AND NOT EXISTS (SELECT 1
                FROM USER_ACCESS_TABLE A
                WHERE A.USER_ID = U.USER_ID
                AND SECURED_OBJECT_ID = 12361511);
                
--ADD APPROVAL AMOUNTS                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'LO_PAY_AP',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'LO_PAY_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'EXP_PAY_AP',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'EXP_PAY_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'LO_RESERV',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'LO_RESERV');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'EXP_RESERV',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'EXP_RESERV');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'CLAIM_AUTH',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'CLAIM_AUTH');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'PC_CMIN_AP',
       'RW',
       '00.01',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'PC_CMIN_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'PC_CMAX_AP',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'PC_CMAX_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'PC_RMIN_AP',
       'RW',
       '00.01',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'PC_RMIN_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'PC_RMAX_AP',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'PC_RMAX_AP');
                
Insert into RESTRICTION_TABLE
   (RESTRICTION_ID, USER_ID, RESTRICTION_TYPE_CODE, ACCESS_TYPE_CODE, RESTRICTED_TO_VALUE_TEXT, 
    CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, ROW_VERSION)
SELECT SEQ_ID.NEXTVAL,
       U.USER_ID,
       'TRIB_DIST',
       'RW',
       '1000000.00',
       'DB SCRIPT',
       SYSDATE,
       'DB SCRIPT',
       SYSDATE,
       1
FROM USER_TABLE U
WHERE
--ONLY ADD FIX CLAIM ACCESS FOR USERS WITH IT-DEV ROLE, IT DEPARTMENT 
EXISTS (SELECT 1
              FROM USER_ROLE_TABLE R
              WHERE R.USER_ID = U.USER_ID
              AND R.SECURITY_ROLE_TYPE_CODE = 'IT_DEV')
--DO NOT ADD THE RESTRICTION IS ALREADY EXISTS
AND NOT EXISTS (SELECT 1
                FROM RESTRICTION_TABLE R
                WHERE R.USER_ID = U.USER_ID
                AND R.RESTRICTION_TYPE_CODE = 'TRIB_DIST');

commit;
exit;
EOF
